swagger:
  enabled: true
  info:
    title: stratio- Microservice API
    description: stratio- Microservice API Description
    version: v1


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.apache: WARN
    org.eclipse: WARN
    com.netflix: INFO

sftphost: 10.20.1.112
sftpuser: motortown_watcher
productsfile: anjana/in/motortown_productos_servicios.csv
stockfile: anjana/in/motortown_stock_por_centro.csv
pricatfile: anjana/in/pricat_ctop.csv
sftpkey: /home/apaniagua/.ssh/id_rsa